branches/cjones8_20150618/TestAndLearn.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestAndLearn.Domain;

namespace TestAndLearn.Web.Controllers
{
    public class SharedController : Controller
    {
        private IUserRepository _userRepository;

        public SharedController(IUserRepository userRepository)
        {
            _userRepository = userRepository;
        }

        public ActionResult MainNavigation(string activeSection)
        {
            var user = _userRepository.GetUser(this.User.Identity.Name);

            return View(new Models.NavigationModel()
            {
                ActiveSection = activeSection,
                CurrentUser = user
            });
        }
    }
}

branches/cjones8_20150618/TestAndLearn.Web/Views/Layouts/_Basic.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="@Url.Content("~/Content/bootstrap/bootstrap-simplex-theme.min.css")" rel="stylesheet">

    <style>
        .col-center-block {
            float: none;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
    </style>
</head>
<body>
    <div>
        @RenderBody()
    </div>

    <!-- Place all script references just before the body closes-->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery/jquery-1.9.1.min.js")"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script type="text/javascript" src="@Url.Content("~/Scripts/bootstrap/bootstrap.min.js")"></script>
</body>
</html>

branches/cjones8_20150618/TestAndLearn.Web/Views/Layouts/_Master.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/jquery/themes/base/minified/jquery-ui.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/jquery/jquery.loadmask.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/jquery/jquery-ui.override.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/jquery/ui.jqgrid.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/jquery/ui.jqgrid-override.css")" rel="stylesheet" />

    <link href="@Url.Content("~/Content/bootstrap/bootstrap.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap/bootstrap-" + Session["ActiveTheme"] + "-theme.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap/bootstrap-callout.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap/bootstrap-slider.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap/bootstrap-datepicker.min.css")" rel="stylesheet" />
    
    <style>
        body 
        {
            padding-top: 50px;
        }

        .row {
            margin-top: 10px;
            margin-bottom: 10px;
        }

        .slide-in-msg {
            border: 1px solid #aaaaaa;
            background-color: white;
        }

        .slide-in-msg p {
            text-align: center;
        }
    </style>
   
    @RenderSection("MoreStyles", false)
</head>
<body>
    @{
        Html.RenderAction("MainNavigation", "Shared", new { activeSection = ViewBag.ActiveSection });
    }

    <div class="container" style="width: 99%">
        @RenderBody()
    </div>

    <!-- Place all script references just before the body closes-->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery/jquery-1.10.2.min.js")"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script type="text/javascript" src="@Url.Content("~/Scripts/bootstrap/bootstrap.min.js")"></script>

    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery/jquery-ui.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery/jquery.form.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery/jquery.json-2.2.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery/jquery.loadmask.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery/jquery-ux-msg.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery/jquery.jqGrid.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery/grid.locale-en.js")"></script>

    <!--
    <script type="text/javascript" src="@Url.Content("~/Scripts/Shared/main-navigation.js")"></script>
    -->
    <script type="text/javascript" src="@Url.Content("~/Scripts/bootstrap/bootstrap-datepicker.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/bootstrap/bootstrap-slider.js")"></script>

    @RenderSection("MoreScripts", false)
</body>
</html>